### ISSUE TITLE
Non-ASCII characters in URLs

### ISSUE THREAD

**Issue by davibicudo** [ivan-rivera/RedditExtractor#1]
After running get_reddit, several warnings came out like this:
43: In file(con, "r") :
  cannot open URL 'https://www.reddit.com/r/sweden/comments/4drp70/sweddit_universalis_ny_s%e4song_alla_v%e4lkomna_s04/.json?limit=500': HTTP status was '400 Bad Request'

Inspecting the url, you may see that the "%e4" characters are causing the problem. The URL works if you substitute it in the browser for ä.

Well done with the wrapper by the way!

**Comment by ivan-rivera** [comment]
Thanks for reporting! I've fixed it (hopefully) in the new version (3.0.0)
