### ISSUE TITLE
get_reddit() >> reddit_content()grepl error on line 62?

### ISSUE THREAD

**Issue by kwartler** [ivan-rivera/RedditExtractor#13]
Can you add `useBytes = TRUE` per [StackOverflow](https://stackoverflow.com/questions/41717781/warning-input-string-not-available-in-this-locale) with grepl?

```
# Error Message in console:
Warning messages:
1: In grepl("^https?://(.*)", URL[i]) :
  input string 1 is invalid in this locale
2: In file(con, "r") :
  cannot open URL 'https://www.reddit.com/r/wallstreetbets/comments/jzsfdp/schr������dinger_sdgr_cat_may_be_dead_this_stock_is/.json?limit=500': HTTP status was '503 Service Unavailable'
```

I think this is the issue [Ö](https://www.reddit.com/r/wallstreetbets/comments/jzsfdp/schr%C3%B6dinger_sdgr_cat_may_be_dead_this_stock_is/) in this post?

I would have done a PR but thought you may have your reasons against this change.

**Comment by ivan-rivera** [comment]
Thanks for reporting. Yes, I'm aware of this issue and it has been fixed in version 3.0.0 which I have just released.
