### ISSUE TITLE
Is there a way to sort by 'Hot'?

### ISSUE THREAD

**Issue by PoLabs** [ivan-rivera/RedditExtractor#2]
There's options for 'comments' and 'new' and also a hidden 'relevance.' But none of these actually show what a reader sees when visiting a subreddit - they see 'Hot' by default. 

I'm also confused as to how the function determines what urls to get:
Example: r/cryptocurrency frontpage currently has ~20 posts with between 10 and 150ish comments. 

`Reddit.cc3 <- reddit_urls(subreddit='CryptoCurrency', page_threshold = 100, cn_threshold = 10, sort_by='comments') `

- this only finds THREE posts with over 10 comments

`Reddit.cc2 <- reddit_urls(subreddit='cryptocurrency', page_threshold = 30, cn_threshold = 1, sort_by='comments') `

- this only finds 17 posts with atleast 1 comment!

No of these are accurate, unless the package is making undocumented decisions on what to return.

Also I'm not sure what 'relevance' is measuring.

**Comment by woodydeck** [comment]
Perhaps you got rate limited by not setting a rate_limit over 2 seconds. The vast majority of posts are orphans, because the majority of redditors posting things are spammers.

**Comment by ivan-rivera** [comment]
Yes, you can now sort by "hot", this is fixed in version 3.0.0
