### ISSUE TITLE
Unable to use any functions of RedditExtractoR

### ISSUE THREAD

**Issue by AshankKumar** [ivan-rivera/RedditExtractor#21]
No matter what function I run I always receive the following error: 

`Error in value[[3L]](cond) : 
  Cannot read from Reddit, check your inputs or internet connection`

For example when I run the following: 

`find_subreddits(keywords="test")`

I get the following error:

`Error in value[[3L]](cond) : 
  Cannot read from Reddit, check your inputs or internet connection
In addition: Warning message:
In file(con, "r") :
  cannot open URL 'https://www.reddit.com/subreddits/search.json?limit=100&q=test': HTTP status was '429 Unknown Error'`

I'm not sure what the issue is as it occurs with any functions of RedditExtractoR

**Comment by ivan-rivera** [comment]
Try running `json <- readLines("https://www.reddit.com/subreddits/search.json?limit=100&q=test")` and let us know what you get. As the error says, it sounds like R cannot connect to the internet.

**Comment by ivan-rivera** [comment]
I presume this us unrelated to the package, so I'm closing this issue for now.
