### ISSUE TITLE
Cannot read from reddit error when knitting RMD

### ISSUE THREAD

**Issue by jfiksel** [ivan-rivera/RedditExtractor#25]
Thanks for the great package! I'm using the package in a .Rmd file, and for some reason when I knit the following code:

```
library(RedditExtractoR)
post_urls <- find_thread_urls(keywords = 'Game Thread: Green Bay Packers vs',
                              subreddit = 'GreenBayPackers', period = "year")
```

I get an error

```
Error in value[[3L]](cond) : Cannot read from Reddit, check your inputs or internet connections
```

However, when I just run the code in my console, I don't have any issues. Do you have any idea what the problem is?

**Comment by ivan-rivera** [comment]
@jfiksel thanks for reporting! I'm afraid that I won't be able to attend to this in the next few days, but I'll investigate when I get the opportunity.
