### ISSUE TITLE
The number of threads retrieved by `find_thread_urls()` is limited to 10 pages

### ISSUE THREAD

**Issue by nthun** [ivan-rivera/RedditExtractor#26]
Thanks for creating and maintaining this package!

```
library(RedditExtractoR)
cats <- find_thread_urls(subreddit="cat", period="all")
#> parsing URLs on page 1...
#> parsing URLs on page 2...
#> parsing URLs on page 3...
#> parsing URLs on page 4...
#> parsing URLs on page 5...
#> parsing URLs on page 6...
#> parsing URLs on page 7...
#> parsing URLs on page 8...
#> parsing URLs on page 9...
#> parsing URLs on page 10...

min(cats$date_utc)
#> [1] "2019-02-08"
nrow(cats)
#> [1] 999
```

**Expected behavior**
The "cat" subreddit was created 13 years ago, so I expect that when I use `period = "all"` I will see all threads related to the subreddit, dating back to 2009. But the function only retrieves 10 pages of threads, with the oldest created in 2019. 

If this behavior is caused by a hard limit in the API, then this should be mentioned in the documentation.

**Comment by ivan-rivera** [comment]
Hey, thanks for using the package! Just wanted to let you know that this behaviour is indeed expected and documented under the FAQ section, see the question "Why can I not get all the comments out of a thread?". This question concerns the behaviour of the Reddit API itself, whereas my package is a minimalistic wrapper of this API. With this in mind, I'm going to close this issue, but feel free to leave a comment if you have other thoughts or questions on this.

**Comment by nthun** [comment]
Yes, I saw in the FAQ that the number of retrieved **comments** is limited, but the issue is about the number of retrieved **threads**.
