### ISSUE TITLE
Please consider giving full date time

### ISSUE THREAD

**Issue by py9mrg** [ivan-rivera/RedditExtractor#27]
Hello,

Please can you consider simplifying:

``` r
timestamp_to_date <- function(timestamp) timestamp |>
  as.POSIXct(origin="1970-01-01") |>
  as.Date() |>
  format("%Y-%m-%d")
```

To 

``` r
timestamp_to_date <- function(timestamp) timestamp |>
  as.POSIXct(origin="1970-01-01")
```

So that we can have more fine-grained comparisons between comment dates (and times)? Or add an option to not simplify to dates?

Thank you.

Edit - I forgot to say, your comment at the end of issue #4, doesn't quite solve this issue because converting back to timestamp from a date, when the time has been dropped, doesn't give the original timestamp.

Here the "round trip" works
```r
timestamp_to_date <- function(timestamp) timestamp |>
  as.POSIXct(origin = "1970-01-01") 

as.numeric(as.POSIXct(timestamp_to_date(1644944045), origin = "1970-01-01"))
[1] 1644944045
```
But here it doesn't
``` r
timestamp_to_date <- function(timestamp) timestamp |>
  as.POSIXct(origin="1970-01-01") |>
  as.Date() |>
  format("%Y-%m-%d")

as.numeric(as.POSIXct(timestamp_to_date(1644944045), origin = "1970-01-01"))
[1] 1644883200
```

**Comment by ivan-rivera** [comment]
Thanks for the suggestion! Yes, perhaps removing the date conversion may be a good idea. I'm afraid that I won't be able to do this for a little while because I'm travelling without my laptop, but feel free to create a PR yourself and I'll approve it. Otherwise, I'll introduce this change myself a little later.

**Comment by py9mrg** [comment]
Yeah no worries, will do. Enjoy your travels!

**Comment by py9mrg** [comment]
Just looking at this now and a couple of questions:

1. the simplest edit is simply to remove the simplification lines above (and edit the tests accordingly). But then we're creating a function to wrap `as.POSIXct(origin = "1970-01-01")`, which seems like overkill. So I could just replace the `timestamp_to_date` function everywhere with `timestamp_to_date`. That also means we can get rid of the tests so simplifies that a bit. But I'll defer to your preference on that.
2. the returned data currently contains `date_utc`. Technically we're now returning a POSIXct so maaaaaybe we should rename the variable accordingly. But I fear (a) I'm being ludicrously pedantic and (b) that might break people's code. So I think probably we should leave that alone.

Let me know what you prefer and I'll finish it off.

**Comment by ivan-rivera** [comment]
How about we simply keep the date fields as they are and add a new fields with the timestamps?

**Comment by py9mrg** [comment]
Yeah, that's a much better idea!
