### ISSUE TITLE
find_thread_urls period="all" does not return all results

### ISSUE THREAD

**Issue by maria-pro** [ivan-rivera/RedditExtractor#32]
**Description**
`find_thread_urls` with `period="all"` does not return all results for a specific subreddit, only top ones. How to actually get urls from ALL threads in the specific subreddit?

**To Reproduce**
`Data_out <- find_thread_urls(subreddit = 'lululemon', sort_by = "new", period="all")`

```
> dim(Data_out)
[1] 989   7
> min(Data_out$date_utc)
[1] "2022-09-26"
```

**Expected behavior**
all urls for a specific subreddit

**Comment by ivan-rivera** [comment]
Hi Maria, sorry it took me a little while to get back to you.

Your concern is addressed in the first item of the FAQ section in the Readme. This is a limitation of the Reddit API itself.

I'm closing this issue.
