### ISSUE TITLE
Improper error trapping of gated content 403 error

### ISSUE THREAD

**Issue by CMolchan1** [ivan-rivera/RedditExtractor#34]
**Describe the bug**
Reddit has gated some content, which the API wrapper doesn't handle properly: 

https://www.reddit.com/r/EDAnonymous/comments/uehq6o/summer_is_coming_pretty_soon_and_im_scared/.json?limit=500 as an example. Visiting the underlying URL at https://www.reddit.com/r/EDAnonymous/comments/uehq6o/summer_is_coming_pretty_soon_and_im_scared/ shows valid results, but the JSON returned above is: 

_`{"interstitial_warning_message_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;This subreddit may contain references or detail about eating disorders, trauma, addictions, or self-injurious and suicidal behavior thatcan be upsetting or triggering for some. &lt;/p&gt;\n\n&lt;p&gt;If you or someone you know is struggling with disordered eating, there are resources that can help. If you are in the US, you can reach out to the National Eating Disorder Association (NEDA) at 1-800-931-2237 by phone or via text. If you are in a crisis and need help immediately, text \u201cNEDA\u201d to 741741 to be connected with a trained volunteer at Crisis Text Line. It provides free, 24/7 support via text message to individuals who are struggling with mental health, including eating disorders, and are experiencing crisis situations. If you are outside the US, feast-ed.org maintains a country-by-country list of organizations that you can contact for help.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;", "reason": "gated", "interstitial_warning_message": "\nThis subreddit may contain references or detail about eating disorders, trauma, addictions, or self-injurious and suicidal behavior thatcan be upsetting or triggering for some. \n\nIf you or someone you know is struggling with disordered eating, there are resources that can help. If you are in the US, you can reach out to the National Eating Disorder Association (NEDA) at 1-800-931-2237 by phone or via text. If you are in a crisis and need help immediately, text \u201cNEDA\u201d to 741741 to be connected with a trained volunteer at Crisis Text Line. It provides free, 24/7 support via text message to individuals who are struggling with mental health, including eating disorders, and are experiencing crisis situations. If you are outside the US, feast-ed.org maintains a country-by-country list of organizations that you can contact for help.\n", "message": "Forbidden", "error": 403}`_

In R, I received the following output: 
```
> HIContents <- get_thread_content(HIUnfilteredThreads$url[3:239])
Error in value[[3L]](cond) : 
  Cannot read from Reddit, check your inputs or internet connection
In addition: Warning message:
In file(con, "r") :
  cannot open URL 'https://www.reddit.com/r/EDAnonymous/comments/uehq6o/summer_is_coming_pretty_soon_and_im_scared/.json?limit=500': HTTP status was '403 Forbidden'
```

I'm attempting to do some data analytics on heat-related illness by aggregating reddit posts, and the 403 resulting from reddit's gating is preventing the return of the remaining valid data.

**To Reproduce**
1. attempt to get_thread_content on a URL that's been gated by reddit
2. . . 
3. broken

**Expected behavior**
trapping of error and exclusion of results which are invalidly formatted or return 403 / 404 / etc errors, and returning the remaining valid results (with an associated warning)

**Comment by CMolchan1** [comment]
Another example can be found at: 

https://www.reddit.com/r/shrooms/comments/yb5lv2/remodeled_the_tent_with_suspended_racks_over_the/.json?limit=500

**Comment by ivan-rivera** [comment]
I opened a [PR](https://github.com/ivan-rivera/RedditExtractor/pull/35), will merge it soon and it should be on CRAN in a few days. Thanks for reporting.

**Comment by CMolchan1** [comment]
First of all, thank you so much for writing the wrapper, and for helping to address my issue!

I'm pretty new to github, and see that you opened a PR, is there anything I have to do on my end to move that forward?

**Comment by ivan-rivera** [comment]
@CMolchan1, no worries at all :)

No, there is nothing that you need to do on your end. I uploaded the update to CRAN, it'll take them a couple of days to process this but when they are done, version 3.0.7 will be available for download. But you don't even have to wait for that, you can install it directly from GitHub with `install_github("ivan-rivera/RedditExtractor")`

**Comment by CMolchan1** [comment]
@ivan-rivera ,
Great, I can't thank you enough.
