### ISSUE TITLE
How to avoid non-available users when extracting info with get_user_content()

### ISSUE THREAD

**Issue by rens713** [ivan-rivera/RedditExtractor#38]
I am using the RedditExtractoR package to obtain information about threads, users, and comments on Reedit. I have a list with different authors, and I am using the function RedditExtractoR::get_user_content, which gives me information about each user from the Oficial Reddit API. The problem is that when I run the code, there are some users that apparently are no longer available, and therefore, the code stops because the API can not obtain their info (they any longer exist). This is the code that I'm using (obviously the list is bigger and it was not constructed with this code, because the authors were extracted from the API with the function find_thread_urls and get_thread_content:

```
list = c("User1","User2",... "UserN")
users_about <- get_user_content(list)

```
The error message that I received is this

```
Error in page[[content_type]] : subscript out of bounds
In addition: Warning messages:
1: In file(con, "r") :
  cannot open URL 'https://www.reddit.com/user/User1.json?limit=100': HTTP status was '403 Forbidden'
2: In h(simpleError(msg, call)) :
  error in evaluating the argument 'content' in selecting a method for function 'fromJSON': cannot open the connection to 'https://www.reddit.com/user/User1.json?limit=100'
Since in the list are two types of users: 1) the ones that are available, 2) the ones that ARE NOT available, I want to make the code still running when that error shows (which means that the API does not recognize that author anymore).
```

The problem is that I can not know which users are available (there only way to do this is manually and I can't do that for 500 users), so, if there is a way to run a code despite the error. In other words, if the information of User 2 is not available on the API, I want the code to ignore that and pull the User3, and so on... Can I do that?

**Comment by ivan-rivera** [comment]
Thanks for reporting this. I'll look into it

**Comment by rens713** [comment]
Thanks a lot for the bugfix, it is working!!!!. I tried extracting the user information from 10 authors and its working, but when I try to extract information from 50 users this error appear:

`Error in page[[content_type]] : subscript out of bounds
In addition: Warning messages:
1: In file(con, "r") :
  cannot open URL 'https://www.reddit.com/user/User1.json?limit=100': HTTP status was '403 Forbidden'
2: In h(simpleError(msg, call)) :
  error in evaluating the argument 'content' in selecting a method for function 'fromJSON': cannot open the connection to 'https://www.reddit.com/user/User1.json?limit=100'
3: In file(con, "r") :
  cannot open URL 'https://www.reddit.com/user/User2.json?limit=100': HTTP status was '403 Forbidden'
4: In h(simpleError(msg, call)) :
  error in evaluating the argument 'content' in selecting a method for function 'fromJSON': cannot open the connection to 'https://www.reddit.com/user/User2.json?limit=100'`

I don't know if this is a problem with the code or the API doesn't allow to pull more information. Thanks a lot for the answer!!

**Comment by rens713** [comment]
[author_example.csv](https://github.com/ivan-rivera/RedditExtractor/files/10991973/author_example.csv)

 Here are the authors that i trying to extract.

**Comment by ivan-rivera** [comment]
Should be fixed now, hopefully!

**Comment by rens713** [comment]
Thanks! I tried but the same error appear and stop the function. In the df that I send, it only goes until number 35. I don't know if it's a problem with the amount of data that R could hold? or the limits that the API established?

**Comment by ivan-rivera** [comment]
Are you actually on version 3.0.9? That list seems to work for me now

**Comment by rens713** [comment]
Yes, thanks! I think that was the problem. Now is fixed! I could obtain all the info, thanks a lot!!
