### ISSUE TITLE
Allows search for: multiple keywords + exact time period

### ISSUE THREAD

**Issue by clara-strasser** [ivan-rivera/RedditExtractor#47]
Hello,

following two feautures would be incredible for research purposes:

1. Allow to search for multiple keywords. For instance keywords = c("food", "drinks",...)
2. Allow to get data for exact time periods. For instance, for the years 2010-2015.

Thank you very much!

I am a great fan of your API wrapper!

**Comment by ivan-rivera** [comment]
Hi Clara, I'm glad you are finding my package useful.

You can search for multiple keywords simply using the OR operator like this: `keywords="food OR drinks"`. This is not a feature of my package; it is just how the Reddit Search API works. As for the dates, unfortunately the Reddit API does not allow that. You can sort by recency and you can also narrow your search to a specific period (e.g. "day" or "month"), that's about it. To look through the Reddit archive, you will need to look at Reddit data dumps like [this one](https://www.reddit.com/r/pushshift/comments/16e0mgg/reddit_data_dumps_for_april_may_june_july_august/).

I hope this helps!
