### ISSUE TITLE
Plugin Appears Broken "Cannot connect to the website, skipping..."

### ISSUE THREAD

**Issue by woodydeck** [ivan-rivera/RedditExtractoR#5]
Today my scripts stopped working with the error message "Cannot connect to the website, skipping...". I tried with multiple IPs and computers, so I am assuming something in the reddit API was deprecated rather than me being banned.

**Comment by AndrSalvi** [comment]
Same for me!

**Comment by woodydeck** [comment]
I forgot about this comment since project is dead. It ended up being a ban I think for me, but it took me a few weeks to figure it out. I now space out my mining on the hourly to avoid an unknown rate limit, and I digest data slowly.

I also updated the plugin to a custom version, primarily scraping the timestamp now, which was broken. https://github.com/ivan-rivera/RedditExtractoR/issues/4
