### ISSUE TITLE
reddit_content is not retrieving all comments from thread

### ISSUE THREAD

**Issue by jimeneztyler** [ivan-rivera/RedditExtractor#7]
First off, awesome package. I'm trying to use reddit_content to retrieve all comments from a thread with ~1,000 comments. When I run the code I am only getting ~350 comments. Am I just hitting the API limit or is something else going on? 

Here is the code that I used:

ei <- reddit_content(URL= "https://www.reddit.com/r/science/comments/cz2ifp/existential_isolation_feeling_alone_in_ones/", wait_time = 2)

**Comment by ivan-rivera** [comment]
I've recently introduced significant updates and bugfixes + added info to the Readme on the behaviour of the Reddit API which limits the max number of comments you can get out of a thread. I'm closing this for now.
