### ISSUE TITLE
RedditExtractor Segfault With Memory [Catalina]

### ISSUE THREAD

**Issue by woodydeck** [ivan-rivera/RedditExtractor#9]
RedditExtractor in Catalina, running R 3.5.2 throws a segfault on scripts that read more than a certain number of pages. I have four identical scripts mining different subreddits. The two heaviest trafficked subs return more results for the 12 hour time period I'm scraping, and error about half way through. The other two scripts successfully complete. Normally the lighter subs take 4 minutes to run, and the heavier ones 10-14 minutes. I run at 3 seconds a comment.

I am running cron jobs for them, and I always output a log. This never happened once before in Mojave, and when downgrading, the behavior stops. If you run the scripts in RStudio, it crashes the whole client when the segfault hits. 

I haven't the foggiest what could be causing this. Please forgive me if this has nothing to do with RedditExtractoR. Below is the traceback. I updated RJSONIO, but had the same result.

```
 *** caught segfault ***
address 0x10f3b3000, cause 'memory not mapped'

Traceback:
 1: readLines(X, warn = FALSE)
 2: RJSONIO::fromJSON(readLines(X, warn = FALSE))
 3: doTryCatch(return(expr), name, parentenv, handler)
 4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5: tryCatchList(expr, classes, parentenv, handlers)
 6: tryCatch(RJSONIO::fromJSON(readLines(X, warn = FALSE)), error = function(e) NULL)
 7: reddit_content(URL, wait_time)
 8: get_reddit(search_terms = NA, regex_filter = "", subreddit = "CryptoCurrency",     cn_threshold = 0, page_threshold = 5, sort_by = "new", wait_time = 3)
An irrecoverable exception occurred. R is aborting now ...
```

**Comment by owenmiller95** [comment]
I am struggling with the same issue. I am running Catalina 10.15.3 and with RStudio Version 1.2.1335. I am now having to split the reddit_content returns into chunks of approximately 25 URLs.

**Comment by ivan-rivera** [comment]
Thanks for reporting and sorry for taking so long to respond. I have recently upgraded the package to version 3.0.0 which now also depends on R 4.1.0. Given this significant upgrade, I'm going to close this issue for now, please re-open it if this happens again on the new version.
